version: '3.8'

services:
  rashifal-go-scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR_NAME=value  # Add any environment variables if needed
